"""add oauth_accounts table

Revision ID: 9416e999b96f
Revises: 003_catalog_tables
Create Date: 2026-05-29 13:19:28.242263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9416e999b96f'
down_revision: Union[str, Sequence[str], None] = '003_catalog_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_capability_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_capabilities_domain'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('capability_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('use_case_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('task_type_target', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bottleneck_keywords', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('works_without_data', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('required_data_types', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('min_history_months_gate', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('min_technical_capability', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('mapped_pain_points', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('primary_outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secondary_outcomes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('time_to_value_weeks_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_to_value_weeks_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('capability_id', name=op.f('capabilities_pkey'))
    )
    op.create_index(op.f('ix_capabilities_domain'), 'capabilities', ['domain'], unique=False)
    op.create_table('products',
    sa.Column('product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('capability_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('vendor', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('integrations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('gdpr_compliant', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deployment_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('pricing_model', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('has_free_tier', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('cost_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cost_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('implementation_effort', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('min_technical_capability', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('setup_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('min_history_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_record_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('works_with_limited_data', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('data_requirement_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.capability_id'], name=op.f('products_capability_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('ix_products_capability_id'), 'products', ['capability_id'], unique=False)
    # ### end Alembic commands ###
