DISCLOSURE_TEXT: str = (
    "Recommendations generated by an AI system (phi4 + SBERT). "
    "Results are advisory — verify before making purchasing decisions."
)

PRIVACY_NOTICE: str = (
    "Operational data you provide is processed to generate recommendations "
    "and stored securely to improve the service. No personal identification "
    "data is required or collected."
)

API_VERSION: str = "0.1.0"

SUPPORTED_LOCALES: tuple[str, ...] = ("en", "de")