DISCLOSURE_TEXT: str = (
    "Recommendations generated by an AI system (phi4 + SBERT). "
    "Results are advisory — verify before making purchasing decisions."
)

PRIVACY_NOTICE: str = (
    "This tool processes company operational data to generate AI-powered "
    "recommendations. No personal data is collected. Session data is not "
    "persisted — your answers are cleared as soon as the recommendation "
    "is returned."
)

API_VERSION: str = "0.1.0"