import sqlite3
import json
import os

DB_PATH = os.path.join(os.path.dirname(__file__), "catalog.db")

SCHEMA = """
CREATE TABLE IF NOT EXISTS capabilities (
    capability_id           TEXT PRIMARY KEY,
    name                    TEXT NOT NULL,
    domain                  TEXT NOT NULL,
    use_case_category       TEXT NOT NULL,
    task_type_target        TEXT NOT NULL,
    description             TEXT NOT NULL,
    bottleneck_keywords     TEXT,
    requires_historical_data    INTEGER NOT NULL DEFAULT 0,
    required_data_types         TEXT,
    works_without_data          INTEGER NOT NULL DEFAULT 1,
    min_history_months_gate     INTEGER,
    min_technical_capability    INTEGER NOT NULL DEFAULT 1,
    primary_outcome             TEXT,
    secondary_outcomes          TEXT,
    time_to_value_weeks_min     INTEGER,
    time_to_value_weeks_max     INTEGER,
    mapped_pain_points          TEXT,
    created_at              TEXT DEFAULT (date('now'))
);

CREATE TABLE IF NOT EXISTS products (
    product_id              TEXT PRIMARY KEY,
    capability_id           TEXT NOT NULL REFERENCES capabilities(capability_id),
    name                    TEXT NOT NULL,
    vendor                  TEXT,
    url                     TEXT,
    integrations            TEXT NOT NULL,
    gdpr_compliant          INTEGER NOT NULL DEFAULT 0,
    deployment_model        TEXT NOT NULL,
    pricing_model           TEXT NOT NULL,
    has_free_tier           INTEGER NOT NULL DEFAULT 0,
    cost_tier               TEXT NOT NULL,
    cost_notes              TEXT,
    implementation_effort   TEXT NOT NULL,
    min_technical_capability INTEGER NOT NULL DEFAULT 1,
    setup_notes             TEXT,
    min_history_months      INTEGER,
    min_record_count        INTEGER,
    works_with_limited_data INTEGER DEFAULT 1,
    data_requirement_notes  TEXT,
    notes                   TEXT,
    created_at              TEXT DEFAULT (date('now'))
);

CREATE INDEX IF NOT EXISTS idx_cap_domain  ON capabilities(domain);
CREATE INDEX IF NOT EXISTS idx_cap_task    ON capabilities(task_type_target);
CREATE INDEX IF NOT EXISTS idx_cap_nodata  ON capabilities(works_without_data);
CREATE INDEX IF NOT EXISTS idx_prod_cap    ON products(capability_id);
CREATE INDEX IF NOT EXISTS idx_prod_cost   ON products(cost_tier);
CREATE INDEX IF NOT EXISTS idx_prod_effort ON products(implementation_effort);
CREATE INDEX IF NOT EXISTS idx_prod_gdpr   ON products(gdpr_compliant);
"""

CAPABILITIES = [
    {
        "capability_id": "ai_crm_intelligence",
        "name": "AI CRM with Lead Scoring and Pipeline Intelligence",
        "domain": "crm_sales",
        "use_case_category": "lead_scoring",
        "task_type_target": "judgment_intensive",
        "description": "AI-powered CRM that automatically scores leads, enriches contact records from web data, predicts deal close probability, surfaces at-risk deals, and deduplicates contacts. Replaces manual CRM hygiene and gut-feel prioritisation with data-driven signals, so sales reps know exactly where to focus.",
        "bottleneck_keywords": "[\"lead prioritisation\", \"which leads to call\", \"pipeline visibility\", \"deal at risk\", \"CRM data quality\", \"missing contact info\", \"lead scoring\", \"sales forecasting\", \"duplicate contacts\", \"manual CRM updates\", \"deal health\"]",
        "requires_historical_data": 1,
        "required_data_types": "[\"crm\", \"orders\"]",
        "works_without_data": 0,
        "min_history_months_gate": 3,
        "min_technical_capability": 1,
        "primary_outcome": "conversion",
        "secondary_outcomes": "[\"accuracy\", \"time_saved\"]",
        "time_to_value_weeks_min": 2,
        "time_to_value_weeks_max": 6,
        "mapped_pain_points": "[\"crm_sales.pipeline.pain_slow_followup\", \"crm_sales.pipeline.pain_unclear_reporting\", \"universal.processes.pain_manual_data_entry\"]",
    },
    {
        "capability_id": "crm_data_enrichment",
        "name": "Automated CRM Data Entry and Enrichment",
        "domain": "crm_sales",
        "use_case_category": "crm_hygiene",
        "task_type_target": "repetitive_routine",
        "description": "Automatically extracts structured information from emails, call notes, and messages and populates CRM fields. Keeps CRM data complete and up to date without manual entry by sales reps.",
        "bottleneck_keywords": "[\"manual CRM entry\", \"CRM data quality\", \"missing fields\", \"CRM hygiene\", \"data entry\", \"updating CRM\", \"CRM not up to date\", \"incomplete records\"]",
        "requires_historical_data": 0,
        "required_data_types": "[\"crm\"]",
        "works_without_data": 0,
        "min_history_months_gate": None,
        "min_technical_capability": 2,
        "primary_outcome": "accuracy",
        "secondary_outcomes": "[\"time_saved\"]",
        "time_to_value_weeks_min": 2,
        "time_to_value_weeks_max": 4,
        "mapped_pain_points": "[\"universal.processes.pain_manual_data_entry\"]",
    },
    {
        "capability_id": "meeting_transcription_crm",
        "name": "AI Meeting Transcription and CRM Sync",
        "domain": "crm_sales",
        "use_case_category": "sales_call_intelligence",
        "task_type_target": "repetitive_routine",
        "description": "Automatically records, transcribes, and summarises sales calls and meetings. Extracts action items, key topics, and next steps. Syncs structured notes directly to CRM records, eliminating manual post-call data entry and ensuring no deal context is lost.",
        "bottleneck_keywords": "[\"manual meeting notes\", \"post-call admin\", \"CRM not updated\", \"forgotten action items\", \"call summaries\", \"meeting notes\", \"sales call recording\", \"transcription\", \"CRM data entry after calls\", \"losing deal context\", \"follow-up missed\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"accuracy\", \"conversion\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 1,
        "mapped_pain_points": "[\"crm_sales.pipeline.pain_slow_followup\", \"universal.processes.pain_manual_data_entry\"]",
    },
    {
        "capability_id": "ai_support_agent",
        "name": "AI Customer Support Agent (Autonomous Resolution)",
        "domain": "customer_support",
        "use_case_category": "autonomous_support",
        "task_type_target": "repetitive_routine",
        "description": "An AI agent that fully resolves customer support conversations without human intervention — answering questions, processing returns, checking order status, and handling policy queries across chat, email, and messaging channels. Charged per resolved conversation, not per message. Hands off to human agents only when resolution is not possible.",
        "bottleneck_keywords": "[\"support volume\", \"24/7 support\", \"agent shortage\", \"repetitive support tickets\", \"customer questions\", \"order status\", \"return requests\", \"policy questions\", \"support costs\", \"chat support\", \"autonomous support\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "cost",
        "secondary_outcomes": "[\"time_saved\", \"response_time\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"universal.processes.pain_repetitive_support\", \"universal.processes.pain_slow_response\", \"universal.processes.pain_ticket_overload\"]",
    },
    {
        "capability_id": "faq_dm_automation",
        "name": "FAQ Automation for Repetitive DM Inquiries",
        "domain": "customer_support",
        "use_case_category": "automated_messaging",
        "task_type_target": "repetitive_routine",
        "description": "Automatically responds to common pre-sale questions arriving via Instagram DM, WhatsApp, or email. Uses rule-based flows or AI to handle repetitive questions about sizing, pricing, shipping, and availability without human intervention.",
        "bottleneck_keywords": "[\"repetitive questions\", \"manual responses\", \"slow reply time\", \"FAQ\", \"pre-sale communication\", \"DM handling\", \"same questions\", \"messaging\", \"inbox\", \"response time\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"response_time\", \"conversion\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"universal.processes.pain_repetitive_support\", \"universal.processes.pain_slow_response\"]",
    },
    {
        "capability_id": "helpdesk_ticket_management",
        "name": "AI-Powered Helpdesk and Ticket Management",
        "domain": "customer_support",
        "use_case_category": "ticket_triage",
        "task_type_target": "mixed",
        "description": "Automatically categorises, prioritises, and routes inbound support tickets across email, chat, and social channels. AI suggests replies based on knowledge base content, detects escalation risk, and tracks SLA compliance. Reduces first response time and manual triage effort for support teams.",
        "bottleneck_keywords": "[\"support tickets\", \"ticket triage\", \"slow response\", \"SLA breach\", \"support overload\", \"manual categorisation\", \"helpdesk\", \"customer service queue\", \"support team overwhelmed\", \"ticket routing\", \"first response time\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"response_time\", \"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 3,
        "mapped_pain_points": "[\"universal.processes.pain_slow_response\", \"universal.processes.pain_ticket_overload\"]",
    },
    {
        "capability_id": "abandoned_cart_recovery",
        "name": "Abandoned Cart and Browse Recovery",
        "domain": "ecommerce_ops",
        "use_case_category": "conversion_recovery",
        "task_type_target": "repetitive_routine",
        "description": "Detects when a visitor adds items to cart or browses products without purchasing and automatically sends a timed follow-up email or message to recover the potential sale. Requires website event tracking to function.",
        "bottleneck_keywords": "[\"low website conversion\", \"visitors not buying\", \"cart abandonment\", \"no follow-up\", \"browse without purchase\", \"website traffic not converting\"]",
        "requires_historical_data": 0,
        "required_data_types": "[\"orders\"]",
        "works_without_data": 0,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "conversion",
        "secondary_outcomes": "[\"time_saved\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"universal.processes.pain_low_marketing_roi\"]",
    },
    {
        "capability_id": "multichannel_order_sync",
        "name": "Multi-channel Order Synchronisation",
        "domain": "ecommerce_ops",
        "use_case_category": "order_management",
        "task_type_target": "repetitive_routine",
        "description": "Automatically pulls orders from multiple sales channels (Instagram, Facebook Shop, marketplace, website) into a single order management system. Eliminates manual order entry from social channels.",
        "bottleneck_keywords": "[\"manual order entry\", \"orders from instagram\", \"facebook orders\", \"channel sync\", \"multiple channels\", \"copy paste orders\", \"social commerce orders\", \"order management\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 2,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 4,
        "mapped_pain_points": "[\"universal.processes.pain_manual_data_entry\"]",
    },
    {
        "capability_id": "order_status_automation",
        "name": "Automated Order Status and Shipping Updates",
        "domain": "ecommerce_ops",
        "use_case_category": "post_purchase_communication",
        "task_type_target": "repetitive_routine",
        "description": "Automatically sends customers proactive order confirmation, shipping notification, and delivery status messages. Eliminates inbound 'where is my order' contacts by pushing updates before customers need to ask.",
        "bottleneck_keywords": "[\"where is my order\", \"shipping update\", \"delivery status\", \"order tracking\", \"post-purchase questions\", \"customer contacts after order\"]",
        "requires_historical_data": 0,
        "required_data_types": "[\"orders\"]",
        "works_without_data": 0,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"response_time\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 3,
        "mapped_pain_points": "[\"universal.processes.pain_repetitive_support\"]",
    },
    {
        "capability_id": "return_management_automation",
        "name": "Return Request Intake and Processing Automation",
        "domain": "ecommerce_ops",
        "use_case_category": "returns_processing",
        "task_type_target": "repetitive_routine",
        "description": "Provides customers with a self-service return request form, automatically generates return labels, and sends status updates throughout the return process. Reduces manual handling time per return case.",
        "bottleneck_keywords": "[\"returns\", \"refunds\", \"return handling\", \"return processing\", \"manual returns\", \"return rate\", \"complaints\", \"exchanges\"]",
        "requires_historical_data": 0,
        "required_data_types": "[\"orders\"]",
        "works_without_data": 0,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"response_time\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 3,
        "mapped_pain_points": "[\"ecommerce_ops.pain_points.pain_manual_returns\"]",
    },
    {
        "capability_id": "campaign_performance_reporting",
        "name": "Unified Marketing Performance Dashboard",
        "domain": "marketing",
        "use_case_category": "performance_reporting",
        "task_type_target": "repetitive_routine",
        "description": "Aggregates performance data from multiple marketing platforms (Meta Ads, email, website analytics) into a single view. Automates weekly reporting and surfaces anomalies without manual data pulling.",
        "bottleneck_keywords": "[\"performance reporting\", \"marketing dashboard\", \"manual reporting\", \"pulling data\", \"multiple platforms\", \"CPA\", \"ROAS\", \"weekly report\", \"campaign analysis\", \"scattered data\"]",
        "requires_historical_data": 1,
        "required_data_types": "[\"marketing\"]",
        "works_without_data": 0,
        "min_history_months_gate": 1,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"universal.processes.pain_no_data_insights\", \"crm_sales.pipeline.pain_unclear_reporting\"]",
    },
    {
        "capability_id": "content_generation_social",
        "name": "AI-Assisted Social Media Content Generation",
        "domain": "marketing",
        "use_case_category": "content_creation",
        "task_type_target": "mixed",
        "description": "Generates product descriptions, social media captions, campaign copy, and content variants from a brief or product information. Reduces time spent on writing and ideation for recurring content needs.",
        "bottleneck_keywords": "[\"content creation\", \"copywriting\", \"social media posts\", \"product descriptions\", \"captions\", \"writing takes time\", \"content burden\", \"campaign copy\", \"design\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"visibility\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 1,
        "mapped_pain_points": "[\"universal.processes.pain_manual_content_creation\"]",
    },
    {
        "capability_id": "email_marketing_personalization",
        "name": "Behavioural Email Marketing Automation",
        "domain": "marketing",
        "use_case_category": "lifecycle_email",
        "task_type_target": "repetitive_routine",
        "description": "Sends personalised email sequences triggered by customer behaviour — first purchase, repeat purchase, inactivity, product browse. Increases customer retention and repeat purchase rate without manual campaign management.",
        "bottleneck_keywords": "[\"email marketing\", \"customer retention\", \"repeat purchase\", \"lifecycle emails\", \"follow-up emails\", \"win-back\", \"personalised emails\", \"customer segments\"]",
        "requires_historical_data": 1,
        "required_data_types": "[\"orders\", \"crm\"]",
        "works_without_data": 0,
        "min_history_months_gate": 3,
        "min_technical_capability": 1,
        "primary_outcome": "conversion",
        "secondary_outcomes": "[\"time_saved\"]",
        "time_to_value_weeks_min": 2,
        "time_to_value_weeks_max": 4,
        "mapped_pain_points": "[\"universal.processes.pain_low_marketing_roi\"]",
    },
    {
        "capability_id": "document_generation",
        "name": "AI-Assisted Document and Report Generation",
        "domain": "operations_backoffice",
        "use_case_category": "document_automation",
        "task_type_target": "mixed",
        "description": "Generates structured documents — proposals, contracts, reports, briefs, post-event summaries — from a set of inputs or a brief. Reduces time spent writing documents from scratch by using templates combined with AI drafting.",
        "bottleneck_keywords": "[\"report generation\", \"proposal writing\", \"document creation\", \"contracts\", \"briefs\", \"writing from scratch\", \"reporting takes time\", \"templates\", \"post-event report\", \"documentation\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"universal.processes.pain_manual_data_entry\", \"universal.processes.pain_manual_invoicing\"]",
    },
    {
        "capability_id": "no_code_workflow_automation",
        "name": "No-Code / Low-Code Workflow Automation",
        "domain": "operations_backoffice",
        "use_case_category": "workflow_automation",
        "task_type_target": "repetitive_routine",
        "description": "Connects business tools via visual workflow builder to automate multi-step processes without writing code — for example: new lead in CRM triggers email sequence, invoice received triggers accounting entry, form submission triggers task creation and Slack notification. Eliminates copy-paste work between systems and manual data transfer across tools.",
        "bottleneck_keywords": "[\"manual data transfer\", \"copy paste between tools\", \"repetitive admin\", \"tools not connected\", \"manual triggers\", \"workflow automation\", \"connecting apps\", \"no integration\", \"process automation\", \"zap\", \"trigger action\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 2,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 4,
        "mapped_pain_points": "[\"universal.processes.pain_manual_data_entry\", \"universal.processes.pain_manual_invoicing\"]",
    },
    {
        "capability_id": "proposal_contract_automation",
        "name": "AI-Assisted Proposal and Contract Generation",
        "domain": "operations_backoffice",
        "use_case_category": "document_automation",
        "task_type_target": "mixed",
        "description": "Generates professional sales proposals, service agreements, and contracts from templates and CRM data. Includes e-signature collection, document tracking (who opened it, which pages viewed), and payment collection. Reduces proposal creation time from hours to minutes and accelerates deal closing.",
        "bottleneck_keywords": "[\"proposal writing\", \"contracts\", \"e-signature\", \"proposal from scratch\", \"slow deal closing\", \"document creation\", \"sales proposals\", \"agreement drafting\", \"legal documents\", \"quote generation\", \"contract signing\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[\"conversion\", \"accuracy\"]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 2,
        "mapped_pain_points": "[\"crm_sales.pipeline.pain_slow_followup\", \"universal.processes.pain_manual_invoicing\"]",
    },
    {
        "capability_id": "demand_forecasting",
        "name": "Demand Forecasting and Inventory Planning",
        "domain": "supply_chain",
        "use_case_category": "inventory_planning",
        "task_type_target": "judgment_intensive",
        "description": "Predicts future product demand based on historical sales data, seasonality patterns, and trends. Helps determine optimal reorder quantities and timing to reduce stockouts and overstock situations.",
        "bottleneck_keywords": "[\"stockout\", \"out of stock\", \"inventory planning\", \"demand forecasting\", \"reorder timing\", \"seasonal demand\", \"gut feeling ordering\", \"over-ordering\", \"stock levels\", \"running low\"]",
        "requires_historical_data": 1,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": 6,
        "min_technical_capability": 1,
        "primary_outcome": "cost",
        "secondary_outcomes": "[\"accuracy\", \"time_saved\"]",
        "time_to_value_weeks_min": 4,
        "time_to_value_weeks_max": 8,
        "mapped_pain_points": "[\"ecommerce_ops.pain_points.pain_inventory_tracking\", \"universal.processes.pain_stockouts\", \"universal.processes.pain_overstock\"]",
    },
    {
        "capability_id": "supplier_communication_assistant",
        "name": "Supplier Communication and RFQ Drafting Assistant",
        "domain": "supply_chain",
        "use_case_category": "procurement_communication",
        "task_type_target": "repetitive_routine",
        "description": "Assists with drafting supplier communication, request-for-quote documents, and order follow-up messages. Reduces time spent on repetitive supplier correspondence and helps standardize communication.",
        "bottleneck_keywords": "[\"supplier communication\", \"RFQ\", \"supplier emails\", \"order follow-up\", \"chasing suppliers\", \"communication with suppliers\", \"quote requests\", \"procurement emails\"]",
        "requires_historical_data": 0,
        "required_data_types": "[]",
        "works_without_data": 1,
        "min_history_months_gate": None,
        "min_technical_capability": 1,
        "primary_outcome": "time_saved",
        "secondary_outcomes": "[]",
        "time_to_value_weeks_min": 1,
        "time_to_value_weeks_max": 1,
        "mapped_pain_points": "[\"universal.processes.pain_supplier_tracking\"]",
    }
]

PRODUCTS = [
    {
        "product_id": "klaviyo_cart",
        "capability_id": "abandoned_cart_recovery",
        "name": "Klaviyo Abandoned Cart Flow",
        "vendor": "Klaviyo",
        "url": "https://klaviyo.com",
        "integrations": "[\"shopify\", \"woocommerce\", \"email\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free up to 250 contacts. Paid from ~$20/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Pre-built flow template. Shopify/WooCommerce integration in 1–2 hours.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Starts capturing events immediately. No historical data needed.",
        "notes": "Industry standard for e-commerce email automation.",
    },
    {
        "product_id": "shopify_abandoned_checkout",
        "capability_id": "abandoned_cart_recovery",
        "name": "Shopify Abandoned Checkout Recovery",
        "vendor": "Shopify",
        "url": "https://shopify.com",
        "integrations": "[\"shopify\", \"email\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "Included in Shopify subscription.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Native feature. Enable in Marketing settings. 15 minutes.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from first abandoned checkout.",
        "notes": "Zero extra cost for Shopify stores. Less customisable than Klaviyo.",
    },
    {
        "product_id": "hubspot_breeze",
        "capability_id": "ai_crm_intelligence",
        "name": "HubSpot CRM with Breeze AI",
        "vendor": "HubSpot",
        "url": "https://hubspot.com",
        "integrations": "[\"gmail\", \"outlook\", \"salesforce\", \"shopify\", \"slack\", \"linkedin\", \"google_ads\", \"meta_ads\", \"zapier\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "medium",
        "cost_notes": "Core CRM is free (unlimited contacts, basic pipeline). Sales Hub Starter from $20/user/month. Professional from $100/user/month. AI features (Breeze Copilot, lead scoring) included in paid tiers. 248,000+ customers across 135 countries.",
        "implementation_effort": "medium",
        "min_technical_capability": 1,
        "setup_notes": "CRM setup takes 1–3 days. AI features activate progressively as data accumulates. Strong onboarding documentation and guided setup.",
        "min_history_months": 3,
        "min_record_count": 100,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Basic CRM works from day 1. Lead scoring and deal predictions improve significantly after 3+ months of contact and deal history.",
        "notes": "Market-leading all-in-one CRM for SMBs. Breeze AI enriches contact records automatically from web data, deduplicates contacts, scores leads, and flags at-risk deals. Free CRM is genuinely powerful. Paid tiers can become expensive as contacts scale but free plan removes the cost barrier for small teams to start. Best fit for B2B companies with a defined sales process.",
    },
    {
        "product_id": "pipedrive_ai",
        "capability_id": "ai_crm_intelligence",
        "name": "Pipedrive with AI Sales Assistant",
        "vendor": "Pipedrive",
        "url": "https://pipedrive.com",
        "integrations": "[\"gmail\", \"outlook\", \"slack\", \"zapier\", \"mailchimp\", \"xero\", \"quickbooks\", \"linkedin\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "Essential $14/user/month, Advanced $29/user/month, Professional $49/user/month, Power $64/user/month (all annual). 14-day free trial. AI Sales Assistant included in Essential and above.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Known for extremely fast onboarding — pipeline live in under 1 hour. Designed specifically for sales teams, not general-purpose CRM.",
        "min_history_months": 1,
        "min_record_count": 10,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from very first deals. AI Sales Assistant provides suggestions even with limited history.",
        "notes": "Best-in-class CRM for pipeline management. AI Sales Assistant suggests next actions, flags stalled deals, and surfaces performance insights. Lower learning curve than HubSpot. Better choice for companies primarily focused on B2B pipeline management without needing marketing automation. 100,000+ companies use Pipedrive.",
    },
    {
        "product_id": "intercom_fin",
        "capability_id": "ai_support_agent",
        "name": "Intercom Fin AI Agent",
        "vendor": "Intercom",
        "url": "https://intercom.com",
        "integrations": "[\"email\", \"chat_widget\", \"whatsapp\", \"sms\", \"zendesk\", \"salesforce\", \"hubspot\", \"shopify\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "Essential plan $29/seat/month. Fin AI Agent charged at $0.99 per resolved conversation on top of seat price. Startup Early Stage program: up to 90% off year 1.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Fin can be deployed in under 1 hour by pointing it at your knowledge base or help centre. Works across chat, email, and as a standalone agent for Zendesk/Salesforce.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Requires a knowledge base, FAQ docs, or policy content to train on. No historical conversation data needed to start.",
        "notes": "Industry-leading AI agent for autonomous resolution. Pay only for successful resolutions ($0.99/outcome) — cost is directly tied to value delivered. Intercom reports average 60%+ resolution rate without human intervention. Can work standalone on top of Zendesk or Salesforce without switching helpdesks.",
    },
    {
        "product_id": "databox",
        "capability_id": "campaign_performance_reporting",
        "name": "Databox",
        "vendor": "Databox Inc.",
        "url": "https://databox.com",
        "integrations": "[\"meta_ads\", \"google_ads\", \"mailchimp\", \"klaviyo\", \"shopify\", \"google_analytics\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free for up to 3 sources. Starter from ~$47/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Pre-built connectors. Dashboard live in 1–2 hours.",
        "min_history_months": 1,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Starts pulling data immediately after connecting sources.",
        "notes": "Best low-effort option for unified marketing reporting.",
    },
    {
        "product_id": "looker_studio",
        "capability_id": "campaign_performance_reporting",
        "name": "Google Looker Studio",
        "vendor": "Google",
        "url": "https://lookerstudio.google.com",
        "integrations": "[\"google_analytics\", \"google_ads\", \"google_sheets\", \"meta_ads\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "free",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free. Some third-party connectors ~$20/mo.",
        "implementation_effort": "medium",
        "min_technical_capability": 2,
        "setup_notes": "Dashboard built from scratch. Setup 4–8 hours.",
        "min_history_months": 1,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from day 1.",
        "notes": "Free but more effort than Databox. Good for Google Workspace users.",
    },
    {
        "product_id": "canva_magic_write",
        "capability_id": "content_generation_social",
        "name": "Canva Magic Write",
        "vendor": "Canva",
        "url": "https://canva.com",
        "integrations": "[\"canva\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Included in Canva Free and Pro (~$13/mo).",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Available inside Canva editor. No separate setup.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed.",
        "notes": "Best fit for companies already using Canva for design.",
    },
    {
        "product_id": "chatgpt_plus_content",
        "capability_id": "content_generation_social",
        "name": "ChatGPT Plus / Claude",
        "vendor": "OpenAI / Anthropic",
        "url": "https://chat.openai.com",
        "integrations": "[\"browser\"]",
        "gdpr_compliant": 0,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free tier available. Plus ~$20/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "No setup. Use via chat interface.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed.",
        "notes": "Most flexible and lowest cost. Requires user to write good prompts.",
    },
    {
        "product_id": "grammarly_business",
        "capability_id": "content_generation_social",
        "name": "Grammarly Business",
        "vendor": "Grammarly",
        "url": "https://grammarly.com/business",
        "integrations": "[\"google_docs\", \"microsoft_word\", \"outlook\", \"gmail\", \"slack\", \"browser_extension\", \"salesforce\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free individual plan available. Business plan $15/user/month (annual, minimum 3 users). Includes AI writing assistance, tone suggestions, brand voice consistency, and style guide enforcement across all team communications.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Browser extension installs in minutes. Works everywhere you type — email, Google Docs, Slack, CRM fields. No training required.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed. Works on any text you write.",
        "notes": "Not a content generator but a writing quality layer applied to all team communications — emails, proposals, support replies, social posts. Business plan adds brand voice settings so all team members write consistently. Particularly valuable for teams where English is not the first language. Works passively without changing any tool or workflow.",
    },
    {
        "product_id": "jasper",
        "capability_id": "content_generation_social",
        "name": "Jasper",
        "vendor": "Jasper AI",
        "url": "https://jasper.ai",
        "integrations": "[\"browser_extension\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "From ~$39/mo per seat.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Browser-based. Brand voice setup takes 1–2 hours.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No company data needed.",
        "notes": "Marketed at marketing teams. Pre-built templates for product descriptions, social captions, campaigns.",
    },
    {
        "product_id": "fireflies_crm_enrichment",
        "capability_id": "crm_data_enrichment",
        "name": "Fireflies.ai (CRM Enrichment via Call Notes)",
        "vendor": "Fireflies",
        "url": "https://fireflies.ai",
        "integrations": "[\"salesforce\", \"hubspot\", \"pipedrive\", \"zoom\", \"google_meet\", \"microsoft_teams\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Pro $10/user/month (annual) required for CRM integrations. Free tier available without CRM sync.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Connect to CRM in Settings. Structured notes (topics, action items, decisions) push automatically after each meeting.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Enriches CRM from first meeting.",
        "notes": "Approaches CRM enrichment from the communication layer — extracts deal data from calls and pushes to CRM records automatically. Does not enrich from web/public data. Best for sales teams losing deal context due to missed call notes.",
    },
    {
        "product_id": "inventory_planner",
        "capability_id": "demand_forecasting",
        "name": "Inventory Planner",
        "vendor": "Inventory Planner",
        "url": "https://inventoryplanner.com",
        "integrations": "[\"shopify\", \"woocommerce\", \"amazon\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "From ~$99/mo. 14-day trial.",
        "implementation_effort": "medium",
        "min_technical_capability": 1,
        "setup_notes": "Native Shopify/WooCommerce integration. Initial sync 1–2 days.",
        "min_history_months": 6,
        "min_record_count": None,
        "works_with_limited_data": 0,
        "data_requirement_notes": "Minimum 6 months sales history stated by vendor.",
        "notes": "Purpose-built for e-commerce inventory forecasting.",
    },
    {
        "product_id": "skubana_linnworks",
        "capability_id": "demand_forecasting",
        "name": "Linnworks (formerly Skubana)",
        "vendor": "Linnworks",
        "url": "https://linnworks.com",
        "integrations": "[\"shopify\", \"amazon\", \"ebay\", \"woocommerce\", \"xero\", \"quickbooks\", \"royal_mail\", \"fedex\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "Pricing from ~$449/month for smaller operations. Custom enterprise pricing for high-volume sellers. Free demo available. Focused on multichannel e-commerce with 50+ orders/day.",
        "implementation_effort": "high",
        "min_technical_capability": 2,
        "setup_notes": "Full onboarding typically 2–4 weeks. Designed for multichannel sellers managing inventory across multiple platforms simultaneously.",
        "min_history_months": 6,
        "min_record_count": 500,
        "works_with_limited_data": 0,
        "data_requirement_notes": "Requires minimum 6 months of sales history across channels for meaningful forecasting. Higher volume operations get better results.",
        "notes": "Best for multichannel e-commerce sellers managing stock across Shopify, Amazon, eBay simultaneously. AI automatically reorders stock before stockouts based on demand patterns. Higher price point justified for sellers processing 50+ orders per day across multiple platforms. Not suitable for small single-channel stores.",
    },
    {
        "product_id": "stocky_shopify",
        "capability_id": "demand_forecasting",
        "name": "Shopify Stocky",
        "vendor": "Shopify",
        "url": "https://apps.shopify.com/stocky",
        "integrations": "[\"shopify\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "free",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free Shopify app.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Install from Shopify App Store.",
        "min_history_months": 3,
        "min_record_count": 100,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works with 3+ months. Less accurate with limited history but functional.",
        "notes": "Free and well-integrated for Shopify stores.",
    },
    {
        "product_id": "chatgpt_docs",
        "capability_id": "document_generation",
        "name": "ChatGPT / Claude for Document Drafting",
        "vendor": "OpenAI / Anthropic",
        "url": "https://chat.openai.com",
        "integrations": "[\"browser\", \"google_docs_extension\"]",
        "gdpr_compliant": 0,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free tier available. Plus ~$20/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "No setup. Paste brief into chat.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed.",
        "notes": "Lowest barrier. Works well for companies with no existing tooling.",
    },
    {
        "product_id": "gamma_ai",
        "capability_id": "document_generation",
        "name": "Gamma",
        "vendor": "Gamma Tech",
        "url": "https://gamma.app",
        "integrations": "[\"browser\", \"google_drive\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free plan: 400 AI credits (~10 presentations). Plus $8/user/month (annual) — unlimited AI generations. Pro $15/user/month.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Browser-based, no install. Type a topic or paste outline, Gamma generates a complete presentation in under 1 minute.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed. Generates from any text description or outline.",
        "notes": "Specifically designed for generating polished presentations, reports, and documents from a brief. Unlike ChatGPT which returns text, Gamma outputs formatted, visually designed slides and documents immediately. Particularly suited for agencies, consultants, and sales teams that frequently produce client-facing presentations. Strong competitor to Canva for structured presentation formats.",
    },
    {
        "product_id": "notion_ai",
        "capability_id": "document_generation",
        "name": "Notion AI",
        "vendor": "Notion Labs",
        "url": "https://notion.so",
        "integrations": "[\"notion\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "~$8/mo per member on top of Notion plan.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Enable in Notion workspace settings.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from any text input. No external data needed.",
        "notes": "Best fit for companies already using Notion.",
    },
    {
        "product_id": "activecampaign",
        "capability_id": "email_marketing_personalization",
        "name": "ActiveCampaign",
        "vendor": "ActiveCampaign",
        "url": "https://activecampaign.com",
        "integrations": "[\"shopify\", \"woocommerce\", \"salesforce\", \"hubspot\", \"wordpress\", \"zapier\", \"stripe\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "Starter from $15/month (1,000 contacts). Plus from $49/month. Professional from $79/month. Pricing scales with contact count, not per user. 14-day free trial.",
        "implementation_effort": "medium",
        "min_technical_capability": 1,
        "setup_notes": "More complex initial setup than Mailchimp but significantly more powerful automation. Onboarding typically 1–2 weeks for full workflow configuration.",
        "min_history_months": 1,
        "min_record_count": 100,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Behavioural triggers start working immediately once tracking is installed. Personalisation improves with accumulated contact activity data.",
        "notes": "Best-in-class for marketing automation combining email, SMS, and CRM in one platform. Rated #1 in customer experience automation on G2 for multiple consecutive years. Predictive sending uses AI to determine optimal send time per individual contact. Strong choice for B2B companies needing both CRM light-touch and email automation in one tool. 180,000+ businesses use it.",
    },
    {
        "product_id": "klaviyo_flows",
        "capability_id": "email_marketing_personalization",
        "name": "Klaviyo Behavioral Flows",
        "vendor": "Klaviyo",
        "url": "https://klaviyo.com",
        "integrations": "[\"shopify\", \"woocommerce\", \"email\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free up to 250 contacts. Scales with list size.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Pre-built flow templates. Shopify/WooCommerce setup in 1–2 hours.",
        "min_history_months": 3,
        "min_record_count": 200,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Flows work immediately. Personalisation improves with more history.",
        "notes": "Industry standard for e-commerce email automation.",
    },
    {
        "product_id": "mailchimp_automations",
        "capability_id": "email_marketing_personalization",
        "name": "Mailchimp Customer Journey Builder",
        "vendor": "Mailchimp",
        "url": "https://mailchimp.com",
        "integrations": "[\"shopify\", \"woocommerce\", \"email\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free up to 500 contacts. Standard from ~$13/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Visual journey builder. Shopify/WooCommerce or API.",
        "min_history_months": 1,
        "min_record_count": 100,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from minimal data.",
        "notes": "More accessible than Klaviyo for beginners.",
    },
    {
        "product_id": "chatgpt_custom_gpt",
        "capability_id": "faq_dm_automation",
        "name": "ChatGPT Custom GPT / API",
        "vendor": "OpenAI",
        "url": "https://openai.com",
        "integrations": "[\"api\"]",
        "gdpr_compliant": 0,
        "deployment_model": "api",
        "pricing_model": "usage",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "~$10–100/mo depending on volume.",
        "implementation_effort": "high",
        "min_technical_capability": 3,
        "setup_notes": "Requires developer to build channel integration.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "FAQ content provided manually. No order history needed.",
        "notes": "Most flexible but highest setup cost. Only suitable with technical staff.",
    },
    {
        "product_id": "manychat",
        "capability_id": "faq_dm_automation",
        "name": "ManyChat",
        "vendor": "ManyChat Inc.",
        "url": "https://manychat.com",
        "integrations": "[\"instagram_dm\", \"whatsapp\", \"facebook\", \"shopify\", \"email\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free up to 1,000 contacts. Pro from ~$15/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "No-code visual flow builder. Instagram and WhatsApp setup in 1–2 days.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Works from day 1.",
        "notes": "Market leader for Instagram DM automation. Best fit for B2C shops with Instagram as primary channel.",
    },
    {
        "product_id": "tidio",
        "capability_id": "faq_dm_automation",
        "name": "Tidio",
        "vendor": "Tidio LLC",
        "url": "https://tidio.com",
        "integrations": "[\"email\", \"chat_widget\", \"shopify\", \"woocommerce\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free tier available. Paid from ~$29/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Shopify plugin or website widget. Setup under 1 hour.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed.",
        "notes": "Stronger for website chat than DM channels.",
    },
    {
        "product_id": "freshdesk_ai",
        "capability_id": "helpdesk_ticket_management",
        "name": "Freshdesk with Freddy AI",
        "vendor": "Freshworks",
        "url": "https://freshdesk.com",
        "integrations": "[\"email\", \"chat_widget\", \"whatsapp\", \"slack\", \"shopify\", \"hubspot\", \"salesforce\", \"jira\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free plan for unlimited agents (basic features). Growth plan $15/agent/month. Pro $49/agent/month. Freddy AI included in Pro and above.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Known for fast onboarding. Basic ticketing live in hours. AI features configured via visual builder.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data required. Free plan available with no time limit.",
        "notes": "Best-value helpdesk for budget-conscious SMEs. Free plan is genuinely useful for small teams. Freddy AI handles suggested replies, ticket summarisation, and sentiment detection.",
    },
    {
        "product_id": "zendesk_ai",
        "capability_id": "helpdesk_ticket_management",
        "name": "Zendesk Suite with AI",
        "vendor": "Zendesk",
        "url": "https://zendesk.com",
        "integrations": "[\"email\", \"chat_widget\", \"slack\", \"salesforce\", \"hubspot\", \"shopify\", \"jira\", \"twitter\", \"facebook\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "Suite Growth $79/agent/month. Advanced AI add-on is an additional $50/agent/month. Startup program: 6 months free for eligible companies under 50 employees.",
        "implementation_effort": "medium",
        "min_technical_capability": 1,
        "setup_notes": "Strong admin UI but configuration of AI workflows and automation rules takes 1–2 weeks for full setup. 1,200+ marketplace integrations available.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from day 1. AI suggestion quality improves as ticket history and knowledge base content grows.",
        "notes": "Market leader in B2B helpdesk. Best for companies with structured support workflows and multi-channel support needs. Overkill for very small teams (<5 support agents).",
    },
    {
        "product_id": "fireflies_ai",
        "capability_id": "meeting_transcription_crm",
        "name": "Fireflies.ai",
        "vendor": "Fireflies",
        "url": "https://fireflies.ai",
        "integrations": "[\"zoom\", \"google_meet\", \"microsoft_teams\", \"salesforce\", \"hubspot\", \"pipedrive\", \"slack\", \"notion\", \"asana\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free tier: unlimited transcription, limited AI summaries, 800 min storage/seat. Pro: $10/user/month (annual). Business: $19/user/month. Free is genuinely functional for individuals.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "AI bot joins meetings automatically via calendar integration. CRM sync configured in Settings. Full setup under 30 minutes.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Works from the first meeting.",
        "notes": "Best choice for teams needing CRM-connected call notes. Supports 69+ languages — strong for multilingual teams. Pushes structured notes to Salesforce, HubSpot, Pipedrive automatically. Pro tier at $10/user/month is strong value.",
    },
    {
        "product_id": "otter_ai",
        "capability_id": "meeting_transcription_crm",
        "name": "Otter.ai",
        "vendor": "Otter.ai",
        "url": "https://otter.ai",
        "integrations": "[\"zoom\", \"google_meet\", \"microsoft_teams\", \"salesforce\", \"dropbox\", \"google_calendar\", \"slack\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free: 300 transcription minutes/month. Pro: $10/user/month (annual) — 1,200 min/month. Business: $20/user/month. Salesforce sync requires Business plan ($20/user).",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Sign up and connect calendar. AI bot joins meetings automatically. First transcription live within hours.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data required. Free plan available with no time limit.",
        "notes": "Best-in-class transcription accuracy for English (2–3% better than competitors in independent testing). Real-time live transcription during meeting. More limited CRM integration than Fireflies — Salesforce sync only on Business plan. Strong choice for smaller teams not needing deep CRM workflows.",
    },
    {
        "product_id": "make_order_sync",
        "capability_id": "multichannel_order_sync",
        "name": "Make (formerly Integromat)",
        "vendor": "Make",
        "url": "https://make.com",
        "integrations": "[\"instagram\", \"facebook\", \"shopify\", \"woocommerce\", \"google_sheets\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free for 1,000 operations/mo. Core from ~$9/mo.",
        "implementation_effort": "medium",
        "min_technical_capability": 2,
        "setup_notes": "Visual scenario builder. More powerful than Zapier. 2–6 hours setup.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed.",
        "notes": "Better value than Zapier at scale. Steeper learning curve.",
    },
    {
        "product_id": "zapier_order_sync",
        "capability_id": "multichannel_order_sync",
        "name": "Zapier",
        "vendor": "Zapier",
        "url": "https://zapier.com",
        "integrations": "[\"instagram\", \"facebook\", \"shopify\", \"woocommerce\", \"google_sheets\", \"email\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free for 100 tasks/mo. Starter from ~$20/mo.",
        "implementation_effort": "medium",
        "min_technical_capability": 2,
        "setup_notes": "No-code but requires trigger/action understanding. 2–4 hours per integration.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Syncs new orders in real time.",
        "notes": "Most flexible — connects almost any two systems.",
    },
    {
        "product_id": "n8n",
        "capability_id": "no_code_workflow_automation",
        "name": "n8n",
        "vendor": "n8n GmbH",
        "url": "https://n8n.io",
        "integrations": "[\"shopify\", \"hubspot\", \"salesforce\", \"slack\", \"gmail\", \"google_sheets\", \"airtable\", \"notion\", \"stripe\", \"api\", \"webhook\"]",
        "gdpr_compliant": 1,
        "deployment_model": "hybrid",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Self-hosted: fully free (open source, requires own server). Cloud Starter: $24/month (2,500 executions). Cloud Pro: $50/month (10,000 executions). Startups under 20 employees get 50% off Business plan. Community of 45,000+ automation builders with pre-built workflow templates.",
        "implementation_effort": "medium",
        "min_technical_capability": 2,
        "setup_notes": "Steeper learning curve than Zapier but significantly more powerful for complex workflows. Visual node-based editor. 400+ built-in integrations. Execution-based pricing (one workflow run = one execution regardless of steps) makes costs predictable.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Works immediately once connected to tools.",
        "notes": "Best automation platform for teams with some technical comfort who want maximum flexibility and data privacy control. Self-hosted version is completely free with unlimited executions — significant cost advantage over Zapier at scale. 400+ integrations including AI nodes for OpenAI, Anthropic. Requires someone comfortable with APIs and logic — not suitable for fully non-technical users.",
    },
    {
        "product_id": "keycrm_shipping_notify",
        "capability_id": "order_status_automation",
        "name": "KeyCRM Built-in Shipping Notifications",
        "vendor": "KeyCRM",
        "url": "https://keycrm.app",
        "integrations": "[\"keycrm\", \"nova_poshta\", \"ukrposhta\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "Included in KeyCRM subscription (~$20–50/mo).",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Native feature in CRM settings. Active in 1 day.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works as soon as orders exist in KeyCRM.",
        "notes": "Specific to Nova Poshta / Ukrposhta delivery services.",
    },
    {
        "product_id": "shopify_flow_shipping",
        "capability_id": "order_status_automation",
        "name": "Shopify Email Notifications",
        "vendor": "Shopify",
        "url": "https://shopify.com",
        "integrations": "[\"shopify\", \"email\", \"sms\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "Included in Shopify subscription. Basic from ~$29/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Built-in templates in Shopify admin. Configure in under 1 hour.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "Works from first order.",
        "notes": "Zero extra cost for Shopify stores.",
    },
    {
        "product_id": "pandadoc",
        "capability_id": "proposal_contract_automation",
        "name": "PandaDoc",
        "vendor": "PandaDoc",
        "url": "https://pandadoc.com",
        "integrations": "[\"salesforce\", \"hubspot\", \"pipedrive\", \"zoho_crm\", \"stripe\", \"paypal\", \"slack\", \"google_docs\", \"api\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free plan: unlimited e-signatures, 3 active documents, basic editor. Essentials: $19/user/month (annual) — unlimited docs, templates, basic CRM integrations. Business: $49/user/month — advanced workflows, analytics, custom branding.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "750+ proposal templates available. CRM integration pulls contact data automatically into documents. Setup 1–2 hours including first template. 14-day free trial on paid plans.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed. Works from day 1.",
        "notes": "60,000+ businesses use PandaDoc. Serves over 60,000 organisations. AI helps draft proposal content and populates CRM field data. Document analytics show which pages recipients read and for how long — actionable signal for follow-up timing. Users report halving proposal creation time. G2 Leader badge in Proposal, Contract Management, Document Generation, and CPQ for 2025.",
    },
    {
        "product_id": "loop_returns",
        "capability_id": "return_management_automation",
        "name": "Loop Returns",
        "vendor": "Loop",
        "url": "https://loopreturns.com",
        "integrations": "[\"shopify\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "medium",
        "cost_notes": "From ~$59/mo.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Shopify app. Branded return portal. Setup 1–2 days.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data required.",
        "notes": "More feature-rich than ReturnGO. Exchange-first approach.",
    },
    {
        "product_id": "returngo",
        "capability_id": "return_management_automation",
        "name": "ReturnGO",
        "vendor": "ReturnGO",
        "url": "https://returngo.ai",
        "integrations": "[\"shopify\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "subscription",
        "has_free_tier": 0,
        "cost_tier": "low",
        "cost_notes": "From ~$23/mo. 14-day trial.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "Shopify app install. Return portal live in 1–2 hours.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No historical data needed.",
        "notes": "Purpose-built return management for Shopify.",
    },
    {
        "product_id": "accio_alibaba",
        "capability_id": "supplier_communication_assistant",
        "name": "Accio (Alibaba AI Sourcing)",
        "vendor": "Alibaba / Accio",
        "url": "https://accio.com",
        "integrations": "[\"alibaba\", \"browser\"]",
        "gdpr_compliant": 0,
        "deployment_model": "saas",
        "pricing_model": "free",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free to use as of 2026. Integrated into Alibaba.com platform. 10+ million monthly active users as of March 2026.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "No setup required. Accessible via Alibaba.com or accio.com directly. Chat interface similar to ChatGPT — type a product or sourcing requirement, get supplier matches with pricing and MOQ data.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No company data needed. User describes sourcing need in natural language.",
        "notes": "AI sourcing assistant built into Alibaba, specifically for finding and evaluating Chinese suppliers. Launched 2024, reached 10+ million monthly users by March 2026. Particularly relevant for businesses sourcing from China. Narrows supplier field from hundreds to a shortlist with pricing and MOQ comparisons, significantly reducing the time spent on supplier research. Human follow-up still required for negotiation. Not GDPR-compliant as data processed on Chinese servers — relevant consideration for EU companies.",
    },
    {
        "product_id": "chatgpt_supplier",
        "capability_id": "supplier_communication_assistant",
        "name": "ChatGPT / Claude for Supplier Drafting",
        "vendor": "OpenAI / Anthropic",
        "url": "https://chat.openai.com",
        "integrations": "[\"browser\"]",
        "gdpr_compliant": 1,
        "deployment_model": "saas",
        "pricing_model": "freemium",
        "has_free_tier": 1,
        "cost_tier": "low",
        "cost_notes": "Free tier available.",
        "implementation_effort": "low",
        "min_technical_capability": 1,
        "setup_notes": "No setup. Use with a standard prompt template.",
        "min_history_months": None,
        "min_record_count": None,
        "works_with_limited_data": 1,
        "data_requirement_notes": "No data needed.",
        "notes": "Does not automate — user must trigger each draft manually.",
    }
]

CAP_KEYS = [
    "capability_id","name","domain","use_case_category","task_type_target",
    "description","bottleneck_keywords","requires_historical_data","required_data_types",
    "works_without_data","min_history_months_gate","min_technical_capability",
    "primary_outcome","secondary_outcomes","time_to_value_weeks_min",
    "time_to_value_weeks_max","mapped_pain_points",
]
PROD_KEYS = [
    "product_id","capability_id","name","vendor","url","integrations","gdpr_compliant",
    "deployment_model","pricing_model","has_free_tier","cost_tier","cost_notes",
    "implementation_effort","min_technical_capability","setup_notes",
    "min_history_months","min_record_count","works_with_limited_data",
    "data_requirement_notes","notes",
]

def build():
    if os.path.exists(DB_PATH):
        os.remove(DB_PATH)
    conn = sqlite3.connect(DB_PATH)
    conn.executescript(SCHEMA)
    conn.executemany(
        f"INSERT INTO capabilities ({','.join(CAP_KEYS)}) VALUES ({','.join(['?']*len(CAP_KEYS))})",
        [[c.get(k) for k in CAP_KEYS] for c in CAPABILITIES],
    )
    conn.executemany(
        f"INSERT INTO products ({','.join(PROD_KEYS)}) VALUES ({','.join(['?']*len(PROD_KEYS))})",
        [[p.get(k) for k in PROD_KEYS] for p in PRODUCTS],
    )
    conn.commit()
    print(f"Built: {len(CAPABILITIES)} capabilities, {len(PRODUCTS)} products\n")
    print("── by domain ──────────────────────────────────────────────")
    for row in conn.execute("SELECT domain, COUNT(*) FROM capabilities GROUP BY domain ORDER BY domain"):
        print(f"  {row[0]:<35} {row[1]} capabilities")
    print("\n── products per capability ────────────────────────────────")
    for row in conn.execute(
        "SELECT c.name, COUNT(p.product_id) FROM capabilities c "
        "LEFT JOIN products p ON c.capability_id=p.capability_id "
        "GROUP BY c.capability_id ORDER BY c.domain"
    ):
        print(f"  {row[0]:<55} {row[1]} products")
    conn.close()
    print(f"\nSaved: {DB_PATH}")

if __name__ == "__main__":
    build()